# -*- coding: utf-8 -*-
"""m22ma012_Q3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UE5SFCefLl0ogQNJoBMJMCLB9IfLpFOd

:**Q3: AREA AND PERIMETER OF A CIRCLE IMAGE**
"""

import cv2 as cv
import numpy as np

img= cv.imread('/content/circle-updated.png')
from google.colab.patches import cv2_imshow
cv2_imshow(img)

img = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
circles = cv2.HoughCircles(img, cv2.HOUGH_GRADIENT, 1, 20,
                           param1=100, param2= 100, minRadius= 0, maxRadius= 0)

data= np.uint16(np.around(circles))

for (x, y, r) in data[0, :]:
   cv.circle(img, (x,y), r, (130,180,190), 3)
   cv.circle(img, (x,y), 2, (0,255,100), -1)

# show the output image
from google.colab.patches import cv2_imshow
cv2_imshow(img)
cv2_imshow(circles)
cv.waitKey(0)
print("coordinates of detected circle's centre, and radius: ", data)
print("the radius of the given circle is: ", r)
print("circumference: ", 2*3.14*r)
print("area: ", 3.14**r*r)
