# -*- coding: utf-8 -*-
"""m22ma012_Q9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ivq6BDmMj1eKjQtFZHph8BH19bw2f4IQ

**Q9: HISTOGRAM EQUAILIZATION**
"""

import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow

img= cv.imread('/content/Amsterdam_Tulpen_Museum_1.jpg')
cv2_imshow(img)

plt.hist(img.ravel(), bins=255)#, [0, 255])
plt.show()

hist,bins = np.histogram(img.flatten(),256,[0,256])
cdf = hist.cumsum()
cdf_normalized = cdf * float(hist.max()) / cdf.max()
plt.plot(cdf_normalized, color = 'b')
plt.hist(img.flatten(),256,[0,256], color = 'r')
plt.xlim([0,256])
plt.legend(('cdf','histogram'), loc = 'upper left')
plt.show()

img = cv.imread('/content/Amsterdam_Tulpen_Museum_1.jpg',0)

''' create a CLAHE object (Arguments are optional).'''
clahe = cv.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
cl1 = clahe.apply(img)

print(cl1.shape)
cv2_imshow(img)
cv2_imshow(cl1)

hist,bins = np.histogram(cl1.flatten(),256,[0,256])
cdf = hist.cumsum()
cdf_normalized = cdf * float(hist.max()) / cdf.max()
plt.plot(cdf_normalized, color = 'b')
plt.hist(img.flatten(),256,[0,256], color = 'r')
plt.xlim([0,256])
plt.legend(('cdf','histogram'), loc = 'upper left')
plt.show()
