# -*- coding: utf-8 -*-
"""m22ma012_Q8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fBdrjQ-wHRcpJfE5IlXxsGtbfn379fHt

**Q8: TEMPLATE MATCHING**
"""

import cv2 as cv
import numpy as np

import cv2 as cv

img= cv.imread('/content/aviral.jpg')
img_grey = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
template= cv.imread('/content/template.PNG')
template_grey = cv.cvtColor(template, cv.COLOR_BGR2GRAY)


h, w= template_grey.shape

method= cv.TM_CCOEFF_NORMED

img2= img_grey.copy()

match= cv.matchTemplate(img2, template_grey, method)
min_value, max_value, min_loc, max_loc= cv.minMaxLoc(match)

location= max_loc

bottom_right= (location[0]+ w, location[1]+ h)

cv.rectangle(img2, location, bottom_right, 0, 5)

from google.colab.patches import cv2_imshow
cv2_imshow(img2)

cv.waitKey(0)
